# Generated by Django 4.1.2 on 2022-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraddress_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
