# Generated by Django 4.1.2 on 2022-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_useraddress_phone_alter_useraddress_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
