# Generated by Django 4.1.2 on 2022-11-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_useraddress_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
