# Generated by Django 4.1.3 on 2022-11-10 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_useraddress_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='id',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
