# Generated by Django 4.1.3 on 2022-11-10 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_useraddress_id_alter_useraddress_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
