# Generated by Django 4.1.3 on 2022-11-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_useraddress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
