# Generated by Django 4.1.2 on 2022-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meal_type',
            field=models.IntegerField(choices=[(1, 'starter'), (2, 'desert'), (3, 'snaks'), (4, 'meal'), (5, 'drinks')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='food_type',
            field=models.IntegerField(choices=[(1, 'veg'), (2, 'non veg')], default=1),
        ),
    ]
