# Generated by Django 4.1.2 on 2022-10-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_meal_type_alter_product_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meal_type',
            field=models.IntegerField(choices=[(1, 'starter'), (2, 'desert'), (3, 'snaks'), (4, 'meal'), (5, 'drinks'), (6, 'street food')], default=1),
        ),
    ]
