# Generated by Django 4.1.2 on 2022-10-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
