# Generated by Django 4.1.2 on 2022-10-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_type',
            field=models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non veg')], default='veg', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='meal_type',
            field=models.CharField(choices=[('starter', 'starter'), ('desert', 'desert'), ('snaks', 'snaks'), ('meal', 'meal'), ('drinks', 'drinks'), ('street food', 'street food')], default='starter', max_length=255),
        ),
    ]
