# Generated by Django 4.1.2 on 2022-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_food_type_alter_product_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meal_type',
            field=models.CharField(choices=[('starter', 'starter'), ('desert', 'desert'), ('snaks', 'snaks'), ('meal', 'meal'), ('drinks', 'drinks'), ('street-food', 'street-food'), ('biryani', 'biryani'), ('salad', 'salad')], default='starter', max_length=255),
        ),
    ]
