# Generated by Django 4.1.2 on 2022-10-31 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_image', models.FileField(default=None, max_length=555, upload_to='restaurant/')),
                ('restaurant_type', models.IntegerField(choices=[(1, 'family'), (2, 'pub'), (3, 'fast-food'), (4, 'dinner'), (5, 'cafe')], default=1)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('pin', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('facilities', models.CharField(max_length=255)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
