# Generated by Django 4.1.2 on 2022-10-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('family', 'family'), ('pub', 'pub'), ('fast-food', 'fast-food'), ('dinner', 'dinner'), ('cafe', 'cafe')], default='family', max_length=255),
        ),
    ]
