# Generated by Django 4.1.2 on 2022-11-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurant_closes_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='facilities',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='available_foodTypes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='home_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
