# Generated by Django 4.1.2 on 2022-11-09 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
