# Generated by Django 4.1.3 on 2022-11-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_picture_product_product_image'),
        ('account', '0011_alter_useraddress_address_id'),
        ('order', '0006_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_email',
            field=models.CharField(default='admin@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
