# Generated by Django 4.1.3 on 2022-11-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_address_email_alter_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
