# Generated by Django 4.1.3 on 2022-11-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_address_order_address_email_order_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
