# Generated by Django 4.1.3 on 2022-11-11 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_address_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
